networks:
  my-net:


services:
  web:
    environment:
      REF_TIMEOUT: 10000

    build: ./frontend

    ports:
      - "8080:80"

    restart: unless-stopped

    networks:
      - my-net

  bweb:
    environment:
      MSERVER_IP: 100.127.73.115 #TO CHANGE #add your minecraft server ip before running
      MSERVER_PORT: 25565 #TO CHANGE (if not default) #default minecraft server port
      PROTOCOL_VERSION: 185 #TO CHANGE #default minecraft protocol version (latest)

    build: ./backend

    restart: unless-stopped

    networks:
      - my-net
